name: ci-vanacheek-pipeline

on:
  schedule:
    - cron: "30 12 * * *" # Запускається о 14:30 за київським часом (UTC+2)
  workflow_dispatch: # Додає можливість запускати вручну

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=list,allure-playwright
        continue-on-error: true

      - name: Install Allure Commandline
        run: npm install allure-commandline --save-dev

      - name: Check Allure Results
        run: ls -la ./allure-results

      - name: Generate Allure Report
        if: always()
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Create Allure Report Screenshot
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              const reportUrl = 'https://vanecheek.github.io/new_IVAN_tests_playwrite';
              await page.goto(reportUrl);
              await page.waitForSelector('//div[@class=\'widgets-grid\']/div/div');
              const locator = await page.locator('//div[@class=\'widgets-grid\']/div/div');
              if (locator) {
              await locator.screenshot({ path: 'allure-report-screenshot.png' });
              } else {
              console.error('Element not found');
              }
              await browser.close();
              })();"

      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          REPO_NAME="new_IVAN_tests_playwrite"
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/"
          MESSAGE="Ебаный скриншот находить не хочет, ГНИДА $REPORT_URL"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d text="$MESSAGE"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendPhoto -F chat_id=$TELEGRAM_CHAT_ID -F photo=@allure-report-screenshot.png
